### ISSUE TITLE
Dataset used in WeakSupervised.sh

### ISSUE THREAD

**Issue by matteopariset** [HazyResearch/ukb-cardiac-mri#1]
I'm trying to run the `WeakSupervised.sh` script but I don't fully understand what data should be used (for example in SEMI parameter in `scaleup_base.sh`) and where I can find the file `ANON_unknown_hack3_gender.csv`
Thanks in advance

**Comment by jason-fries** [comment]
Hi @matteopariset,

Sorry for the confusion -- those scripts largely deal with our internal workflow and require access to the full UK Biobank dataset. As such they're not really meant for public use. 

The weak supervision part of the paper is covered in these [two Jupyter notebooks ](https://github.com/HazyResearch/ukb-cardiac-mri/tree/master/notebooks). We've also provided a demo of our end model (CNN-LSTM) that uses labeled MRI data [here](https://github.com/HazyResearch/ukb-cardiac-mri#iii-how-to-use).

We're in the process of putting together a new end-to-end demo that should be easier to use and is built using our upcoming Snorkel v0.9 release. That should come online by the end of August.

Thanks for the interest!

**Comment by matteopariset** [comment]
Thank you for the very fast reply.
I look forward to trying out the new material
